%Doctor.Config{
  # Internal helpers are not part of the public API, and Doctor cannot infer
  # specs for functions generated by the provider contract macro.
  ignore_modules: [
    Jido.Memory.Helpers,
    Jido.Memory.Testing.ProviderContractCase
  ],
  ignore_paths: [~r|^test/support/|],
  min_module_doc_coverage: 100,
  min_module_spec_coverage: 100,
  min_overall_doc_coverage: 100,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 100,
  exception_moduledoc_required: true,
  reporter: Doctor.Reporters.Summary,
  struct_type_spec_required: true
}
